example/src/screens/NetworkClientScreen.tsx, src/ApiClient/index.tsx, src/ApiClient/types.tsx
* Update the JS API to include a patch method.
* Typo fixes
=> fix: add patch method and fix various typos

example/ios/NetworkClientExample.xcodeproj/project.pbxproj, example/ios/Podfile.lock, example/package-lock.json, example/package.json, example/src/components/MethodPicker.tsx, example/src/screens/GenericClientScreen.tsx, example/src/screens/NetworkClientScreen.tsx, src/ApiClient/index.tsx
* Added missing CRUD methods to the GenericClient
* Updated the example app with a dropdown picker for the request method
* Note: There's a lot of duplication in the example app's Generic and Network client screens which will be fixed in a future PR (see https://mattermost.atlassian.net/browse/MM-30107)
https://mattermost.atlassian.net/browse/MM-30106
=> [MM-30106] JS API - add CRUD methods to GenericClient

@types/APIClients.ts, android/src/main/java/com/mattermost/networkclient/APIClientModule.kt, android/src/main/java/com/mattermost/networkclient/GenericClientModule.kt, android/src/main/java/com/mattermost/networkclient/Helper.kt, src/index.tsx
A basic `APIClient` is introduced for Android. Further PR's will allow the handling of various configuration options per client / request.
=> Introduces base "APIClient" for Android

android/src/main/java/com/mattermost/networkclient/APIClientModule.kt, android/src/main/java/com/mattermost/networkclient/GenericClientModule.kt, android/src/main/java/com/mattermost/networkclient/Helper.kt, android/src/main/java/com/mattermost/networkclient/NetworkClientPackage.kt, android/src/main/java/com/mattermost/networkclient/NetworkConstants.kt, example/android/build.gradle, example/src/screens/APIClientScreen.tsx, example/src/screens/CreateAPIClientScreen.tsx, example/src/screens/GenericClientScreen.tsx
PR split - introduces follow-redirect config option on the client.
Note: This requires merging in `android/network-client`.
=>  [MM-30121] Android - Follows Redirect

android/src/main/java/com/mattermost/networkclient/Helper.kt, android/src/main/java/com/mattermost/networkclient/RetryInterceptor.kt
Introduces connection retries for Android
Jira: https://mattermost.atlassian.net/browse/MM-30124
=> [MM-30124] Android retry connection / connection timeout

example/@types/navigation.ts, example/src/screens/GenericClientRequestScreen.tsx, ios/NetworkClient.swift
Fixes Generic Client bugs found by @josephbaylon
=> Fix hard coded method and navigation prop

android/src/main/java/com/mattermost/networkclient/Helper.kt, android/src/main/java/com/mattermost/networkclient/NetworkClientPackage.kt, android/src/main/java/com/mattermost/networkclient/WebSocketClientModule.kt, android/src/main/java/com/mattermost/networkclient/enums/WebSocketEvents.kt, android/src/main/java/com/mattermost/networkclient/enums/WebSocketReadyState.kt, android/src/main/java/com/mattermost/networkclient/events/WebSocketEvent.kt, example/package-lock.json, example/src/utils/index.tsx, ios/APIClient.swift
Introduces websocket support for Android.
Resolves https://mattermost.atlassian.net/browse/MM-31903?atlOrigin=eyJpIjoiODA4NzUyNzNmYzM4NGE2OTk5YzUyNTZjMjM3NTk0ZGYiLCJwIjoiaiJ9
=> [MM-31903] Android Websockets

android/src/main/java/com/mattermost/networkclient/APIClientModule.kt, android/src/main/java/com/mattermost/networkclient/WebSocketClientModule.kt
Invalidates (removes) a websocket client.
https://mattermost.atlassian.net/browse/MM-34221
=> [MM-34221] Invalidate Websocket Client (Android)

@types/APIClients.ts, example/src/screens/APIClientUploadScreen.tsx, ios/APIClient.swift, ios/NetworkClient.swift
Allows for multipart uploads on iOS
https://mattermost.atlassian.net/browse/MM-34218
=> [MM-34218] iOS - support multipart uploads

example/detox/e2e/support/test_config.js
Forgot to update the urls to point to master during merge of https://github.com/mattermost/react-native-network-client/pull/57
NA
=> Detox/E2E: Update urls to master

android/src/main/java/com/mattermost/networkclient/APIClientModule.kt, android/src/main/java/com/mattermost/networkclient/Extensions.kt, android/src/main/java/com/mattermost/networkclient/GenericClientModule.kt, android/src/main/java/com/mattermost/networkclient/NetworkClient.kt, android/src/main/java/com/mattermost/networkclient/helpers/UploadProgressListener.kt, android/src/main/java/com/mattermost/networkclient/helpers/UploadRequestBody.kt, src/APIClient/index.tsx
* Check if `skipBytes` is in options before retrieving value
* Refactor upload classes to take in less params
* Parse response body to WritableMap
Tested on community by uploading an image as a post and by updating a user's avatar.
https://mattermost.atlassian.net/browse/MM-35347
=> [MM-35347] Fix Android uploads

android/src/main/java/com/mattermost/networkclient/APIClientModule.kt, android/src/main/java/com/mattermost/networkclient/Extensions.kt, android/src/main/java/com/mattermost/networkclient/GenericClientModule.kt, android/src/main/java/com/mattermost/networkclient/NetworkClient.kt, android/src/main/java/com/mattermost/networkclient/WebSocketClientModule.kt, android/src/main/java/com/mattermost/networkclient/WebSocketEventListener.kt, android/src/main/java/com/mattermost/networkclient/helpers/UploadProgressListener.kt, android/src/main/java/com/mattermost/networkclient/helpers/UploadRequestBody.kt, android/src/main/java/com/mattermost/networkclient/interceptors/RuntimeInterceptor.kt, android/src/main/java/com/mattermost/networkclient/interceptors/TimeoutInterceptor.kt
* Add a second NetworkClient constructor to pass in the WS URI
* Construct the WS Request from the URI
* Clean up WS event handlers
Tested with local MM server and could connect, send, receive, and disconnect.
https://mattermost.atlassian.net/browse/MM-35349
=> [MM-35349] Fix Android WebSocketClient

README.md
Explains need for writing this library.
=> Add About section

@types/APIClients.ts, @types/NativeAPIClient.ts, @types/NativeGenericClient.ts, android/src/main/java/com/mattermost/networkclient/GenericClientModule.kt, example/src/screens/APIClientRequestScreen.tsx, example/src/screens/GenericClientRequestScreen.tsx, example/src/utils/index.tsx, ios/APIClient.m, ios/APIClient.swift, ios/GenericClient.m, ios/GenericClient.swift, src/APIClient/index.tsx, src/GenericClient/index.tsx
=> Support making `head` requests

android/src/main/java/com/mattermost/networkclient/APIClientModule.kt, android/src/main/java/com/mattermost/networkclient/GenericClientModule.kt, android/src/main/java/com/mattermost/networkclient/NetworkClient.kt, example/detox/e2e/test/helpers.js, example/metro.config.js
Previously the Requests on Android were blocking the UI Thread as they were executed synchronously, this PR makes the request to be executed async.
@josephbaylon can you please run the E2E tests for Android?
=> fix: make android requests async

android/src/main/java/com/mattermost/networkclient/APIClientModule.kt, android/src/main/java/com/mattermost/networkclient/Extensions.kt, android/src/main/java/com/mattermost/networkclient/NetworkClient.kt, android/src/main/java/com/mattermost/networkclient/enums/APIClientEvents.kt, android/src/main/java/com/mattermost/networkclient/helpers/ProgressListener.kt, android/src/main/java/com/mattermost/networkclient/helpers/ProgressResponseBody.kt, android/src/main/java/com/mattermost/networkclient/helpers/UploadRequestBody.kt, android/src/main/java/com/mattermost/networkclient/interceptors/DownloadProgressInterceptor.kt, example/@types/navigation.ts, example/ios/Podfile, example/ios/Podfile.lock, example/ios/patches/SessionDelegate.patch, example/src/App.tsx, example/src/screens/APIClientDownloadScreen.tsx, example/src/screens/APIClientRequestScreen.tsx, example/src/screens/APIClientScreen.tsx, example/src/screens/CreateAPIClientScreen.tsx, example/src/utils/index.tsx, ios/APIClient.m, ios/APIClient.swift, ios/NetworkClient.swift, src/APIClient/index.tsx, src/types/APIClient.ts, src/types/NativeAPIClient.ts
* Fixed uploads on Android so they are not blocking and multiple uploads can be performed at the same time.
* Added download with progress indicator on Android and it saves the file to the specified path.
Pending
* iOS download with progress and saving the file
* JS implementation of the download method
=> Upload & Download

android/src/main/java/com/mattermost/networkclient/helpers/ProgressListener.kt
This fixed crash on Android with non english numeric locale.
See this SO answer and corresponding question: https://stackoverflow.com/a/49432344
=> fix crash on Android when default locale format numbers with comma

src/APIClient/index.tsx
removes top level domain verification
=> fix: remove validation for tld

android/src/main/java/com/mattermost/networkclient/WebSocketClientModule.kt, ios/WebSocketClient.m, ios/WebSocketClient.swift, ios/WebSocketManager.swift, src/WebSocketClient/index.tsx, src/types/NativeWebSocketClient.ts
Fix iOS invalidation and improve not creating multiple clients for the same url
None
=> Fix iOS invalidation and improve not creating multiple clients for the same url

android/src/main/java/com/mattermost/networkclient/ApiClientModuleImpl.kt
On Android, we were decrypting the bearer token for every request we were making, and this was causing problems specially on Android 15. With this PR, we created a map that will hold the token in memory for quicker access without having to decrypt every time.
=> perf(android): add a cache object to avoid having to decrypt the alias in every access

android/src/main/AndroidManifest.xml, android/src/main/java/com/mattermost/networkclient/ApiClientModuleImpl.kt, android/src/main/java/com/mattermost/networkclient/Extensions.kt, android/src/main/java/com/mattermost/networkclient/NetworkClient.kt, android/src/main/java/com/mattermost/networkclient/WebSocketClientModuleImpl.kt, android/src/main/java/com/mattermost/networkclient/interceptors/CompressedResponseSizeInterceptor.kt, android/src/main/java/com/mattermost/networkclient/metrics/MetricsEventFactory.kt, android/src/main/java/com/mattermost/networkclient/metrics/MetricsEventListener.kt, android/src/main/java/com/mattermost/networkclient/metrics/NetworkType.kt, android/src/main/java/com/mattermost/networkclient/metrics/RequestMetadata.kt, ios/ApiClient/ApiClientWrapper.swift, ios/Extensions/Session+Extensions.swift, ios/Extensions/URLSessionTaskTransactionMetrics+Extensions.swift, ios/NetworkClient.swift, ios/SessionManager.swift, src/APIClient/NativeApiClient.ts, src/types/APIClient.ts
This PR introduces the capability to collect metrics for requests in a session
https://mattermost.atlassian.net/browse/MM-61877
=> feat: collect metrics for requests
