- example/src/screens/NetworkClientScreen.tsx
- src/ApiClient/index.tsx
- src/ApiClient/types.tsx
* Add `Promise<Response>` return type for CRUD methods. The `Response` type is a WIP and includes optional headers and data for now so that we know what the example app expects as a response
* Include body in POST request
> fix: add return type to CRUD methods

- @types/APIClients.ts
- @types/NativeConstants.ts
- android/src/main/java/com/mattermost/networkclient/NetworkConstants.kt
- src/Constants/index.ts
This adds the `EXPONENTIAL_RETRY` constant for android, and should allow the example to build.
> Android: Native Constants 

- example/ios/SDWebImageDownloaderOperation+initWithRequest.m
- example/src/screens/APIClientFastImageScreen.tsx
- example/src/screens/APIClientRequestScreen.tsx
- example/src/utils/index.tsx
- ios/APIClient.swift
- ios/BearerAuthenticationAdapter.swift
- ios/NetworkClient.swift
- ios/Session+NetworkClient.swift
- ios/SessionManager.swift
This is based on https://github.com/mattermost/react-native-network-client/pull/23. Changes for this PR are in commit https://github.com/mattermost/react-native-network-client/commit/518f4a395d9eda0dce18b7be4ffc5ba63b21258c.
When swizzling SDWebImageDownloader for RN Fast Image, it was easy to find our own session for the image request if we created sessions by using the `host` value rather than the supplied `baseUrl`, since we can easily get the `host` from `request.host` in SDWebImageDownloader. This, however, introduces some other problems (see this [mattermost conversation](https://community.mattermost.com/core/pl/1r89uyif8tf6m8rb5ogrqmqtyy)). This PR reverts back to using the baseUrl for session creation and updates the swizzled SDWebImageDowloader to use a new SessionManager …
> Revert back to creating sessions using baseUrl instead of host

- ios/APIClient.swift
Fixes error
```
method 'constantsToExport()' with Objective-C selector 'constantsToExport' conflicts with method 'constantsToExport()' from superclass 'RCTEventEmitter' with the same Objective-C selector
```
> Fix APIClient's constantsToExports

- example/MOCKSERVER.md
- example/README.md
- example/detox/e2e/support/ui/component/alert.js
- example/detox/e2e/support/ui/component/retry_policy_configuration.js
- example/detox/e2e/support/ui/screen/api_client.js
- example/detox/e2e/support/ui/screen/client_list.js
- example/detox/e2e/support/ui/screen/create_api_client.js
- example/detox/e2e/support/ui/screen/create_web_socket_client.js
- example/detox/e2e/support/ui/screen/generic_client_request.js
- example/detox/e2e/support/utils.js
- example/detox/e2e/test/client/create_api_client.e2e.js
- example/detox/e2e/test/delete/delete_api_client_request.e2e.js
- example/detox/e2e/test/delete/delete_generic_client_request.e2e.js
- example/detox/e2e/test/get/get_api_client_request.e2e.js
- example/detox/e2e/test/get/get_generic_client_request.e2e.js
- example/detox/e2e/test/helpers.js
- example/detox/e2e/test/patch/patch_api_client_request.e2e.js
- example/detox/e2e/test/patch/patch_generic_client_request.e2e.js
- example/detox/e2e/test/post/post_api_client_request.e2e.js
- example/detox/e2e/test/post/post_generic_client_request.e2e.js
- example/detox/e2e/test/put/put_api_client_request.e2e.js
- example/detox/e2e/test/put/put_generic_client_request.e2e.js
- example/src/components/RetryPolicyConfiguration.tsx
- example/src/screens/APIClientScreen.tsx
- example/src/screens/CreateAPIClientScreen.tsx
- example/src/screens/CreateWebSocketClientScreen.tsx
- example/src/utils/index.tsx
- Added e2e for create API client `e2e/test/client/create_api_client.e2e.js`
- Added checkbox helper functions on screen objects
- Added API client screen verifications on related E2Es and some cleanup
- Made display of added headers ordered in API client screen
- Fixed formatting on docs
Note: These changes are also for Android. However, since Android app still has issues that prevent e2e testing, I only assigned the iOS ticket to this PR. I will retest on Android once issues have been fixed [MM-32806](https://mattermost.atlassian.net/browse/MM-32806), [MM-32681](https://mattermost.atlassian.net/browse/MM-32681), [MM-32685](https://mattermost.atlassian.net/browse/MM-32685)
JIRA: https://mattermost.atlassian.net/browse/MM-32242
> MM-32242 Detox E2E: Add iOS e2e for create API client

- ios/SessionManager.swift
Ensures that when decomposing a requested URL we account for the port number if it exists.
> Account for requestUrl port when swizzling FastImage

- example/MOCKSERVER.md
- example/detox/e2e/support/ui/component/add_headers.js
- example/detox/e2e/support/ui/component/header_list_item.js
- example/detox/e2e/support/ui/screen/api_client.js
- example/detox/e2e/support/ui/screen/api_client_fast_image.js
- example/detox/e2e/support/ui/screen/api_client_request.js
- example/detox/e2e/support/ui/screen/api_client_upload.js
- example/detox/e2e/support/ui/screen/client_list.js
- example/detox/e2e/support/ui/screen/create_api_client.js
- example/detox/e2e/support/ui/screen/create_web_socket_client.js
- example/detox/e2e/support/ui/screen/generic_client_request.js
- example/detox/e2e/test/client/create_api_client.e2e.js
- example/detox/e2e/test/delete/delete_api_client_request.e2e.js
- example/detox/e2e/test/fast_image/fast_image_cookie_token_api_client_request.e2e.js
- example/detox/e2e/test/fast_image/fast_image_header_token_api_client_request.e2e.js
- example/detox/e2e/test/fast_image/fast_image_regular_api_client_request.e2e.js
- example/detox/e2e/test/get/get_api_client_request.e2e.js
- example/detox/e2e/test/patch/patch_api_client_request.e2e.js
- example/detox/e2e/test/post/post_api_client_request.e2e.js
- example/detox/e2e/test/put/put_api_client_request.e2e.js
- example/detox/e2e/test/upload/upload_api_client_request.e2e.js
- example/mockserver.js
- example/package-lock.json
- example/package.json
- example/src/components/AddHeaders.tsx
- example/src/components/HeaderListItem.tsx
- example/src/components/ListHeaders.tsx
- example/src/screens/APIClientScreen.tsx
- example/src/screens/ClientListScreen.tsx
- Fixed e2e tests, components, screens to adapt to android example app
- Added new testIDs
- Pulled mockserver to local file so that we have more control on how it is used (npm sometimes installs the wrong mockserver using `npm install mockserver`)
Note: All e2e tests passed for iOS. For android, most passed except for `upload_api_client_request` e2e test, which is expected because https://github.com/mattermost/react-native-network-client/pull/32 hasn't been tested and merged yet (see results below)
JIRA:
- https://mattermost.atlassian.net/browse/MM-32807
- https://mattermost.atlassian.net/browse/MM-32243
|iOS Results|Android Results|
|:---|:---|
|![Screen Shot 2021-03-11 at 11 15 00 AM](https://user-images.githubusercontent.com/487991/110842519-0a84a780-825c-11eb-9de0-d7f1fc22f22b.png)|![ …
> [MM-32243, MM-32807] Detox/E2E: Sample Android E2E for creating api client, generic and api clients requests

- example/detox/e2e/support/ui/component/response_error_overlay.js
- example/detox/e2e/support/ui/component/response_success_overlay.js
- example/detox/e2e/support/ui/component/retry_policy_configuration.js
- example/detox/e2e/support/ui/screen/api_client_request.js
- example/detox/e2e/support/ui/screen/create_api_client.js
- example/detox/e2e/support/ui/screen/create_websocket_client.js
- example/detox/e2e/support/ui/screen/generic_client_request.js
- example/detox/e2e/test/delete/delete_api_client_request.e2e.js
- example/detox/e2e/test/delete/delete_generic_client_request.e2e.js
- example/detox/e2e/test/get/get_api_client_request.e2e.js
- example/detox/e2e/test/get/get_generic_client_request.e2e.js
- example/detox/e2e/test/helpers.js
- example/detox/e2e/test/patch/patch_api_client_request.e2e.js
- example/detox/e2e/test/patch/patch_generic_client_request.e2e.js
- example/detox/e2e/test/post/post_api_client_request.e2e.js
- example/detox/e2e/test/post/post_generic_client_request.e2e.js
- example/detox/e2e/test/put/put_api_client_request.e2e.js
- example/detox/e2e/test/put/put_generic_client_request.e2e.js
- example/detox/e2e/test/setup/create_api_client.e2e.js
- example/detox/e2e/test/setup/create_websocket_client.e2e.js
- example/detox/e2e/test/setup/error_api_client_request.e2e.js
- example/detox/e2e/test/setup/error_generic_client_request.e2e.js
- example/detox/e2e/test/websocket/websocket_client_request.e2e.js
- Added sample tests for client errors
- `example/detox/e2e/test/setup/error_api_client_request.e2e.js`
- `example/detox/e2e/test/setup/error_generic_client_request.e2e.js`
- Added `verifyResponseErrorOverlay` to `helpers.js`
- The rest of the changes are minor improvements
- Made sure numerical parameters are passed as numbers instead of string
- Refactored `createApiClient` and `createWebSocketClient` to `helpers.js`
- Added/fixed function comments on `helpers.js`
- Updated affected tests and some cleanup
https://mattermost.atlassian.net/browse/MM-34139
Note: `patch/post` failing tests are known issues (fix is being worked here: https://github.com/mattermost/react-native-network-client/pull/53)
> MM-34139 Detox/E2E: Sample iOS E2E for client errors

- README.md
- android/build.gradle
- android/src/main/java/com/mattermost/networkclient/APIClientModule.kt
- android/src/main/java/com/mattermost/networkclient/Extensions.kt
- android/src/main/java/com/mattermost/networkclient/NetworkClient.kt
- android/src/main/java/com/mattermost/networkclient/enums/APIClientEvents.kt
- android/src/main/java/com/mattermost/networkclient/helpers/DocumentHelper.java
- android/src/main/java/com/mattermost/networkclient/helpers/KeyStoreHelper.kt
- android/src/main/java/com/mattermost/networkclient/interceptors/BearerTokenInterceptor.kt
- example/android/app/src/main/AndroidManifest.xml
- example/src/components/P12Inputs.tsx
- src/APIClient/index.tsx
Importing of the client certificate is done by:
1. Loading the user provided P12 file as a PKCS12 KeyStore
2. Looping through aliases
3. Grabbing only the first entry that is key entry
4. Loading a new PKCS12 KeyStore
5. Writing the key and certificate entries into this new KeyStore
6. Creating a file using `APIClientModule.context.openFileInput` and storing the KeyStore there using the user provided password
7. Encrypting the password and storing in SharedPreferences
1. Retrieve and decrypt the password from SharedPreferences
2. Load our created PKCS12 KeyStore using the password
3. Retrieve the private key, client certificate, and intermediate certificates from the KeyStore and use them to create an OkHttp3 HeldCertificate which is then used to build a HandshakeCertificates
4. Use the …
> [MM-30594, MM-34376] Android: Client certificate

- @types/APIClients.ts
- android/src/main/java/com/mattermost/networkclient/Extensions.kt
- android/src/main/java/com/mattermost/networkclient/GenericClientModule.kt
- android/src/main/java/com/mattermost/networkclient/NetworkClient.kt
- example/detox/e2e/support/ui/component/response_success_overlay.js
- example/detox/e2e/support/ui/screen/create_api_client.js
- example/detox/e2e/test/helpers.js
- example/src/components/ResponseSuccessOverlay.tsx
- example/src/hooks/index.tsx
- example/src/screens/CreateAPIClientScreen.tsx
- example/src/utils/index.tsx
- ios/APIClient.swift
- ios/GenericClient.swift
- ios/NetworkClient.swift
- src/APIClient/index.tsx
- src/schemas.tsx
* GenericClient requests will follow all redirects and return a list of redirect URLs via `response.redirectUrls`
* APIClient requests will not follow redirects
GenericClient request (Android and iOS):
APIClient request (Android and iOS):
> Follow redirects only for GenericClient

- android/src/main/java/com/mattermost/networkclient/NetworkClient.kt
- ios/APIClient.swift
* Cannot use `appendingPathComponent` since the `endpoint` value might contain a query string; Instead just concatenate the baseUrl with the endpoint
* `requestRetriesExhausted` is a HashMap with `response` keys, not `request`
> Fix issues found while integrating into mattermost-mobile

- android/src/main/java/com/mattermost/networkclient/APIClientModule.kt
- android/src/main/java/com/mattermost/networkclient/Extensions.kt
- android/src/main/java/com/mattermost/networkclient/GenericClientModule.kt
- android/src/main/java/com/mattermost/networkclient/NetworkClient.kt
* Android Generic client to have options set as optional
* Android invalidate to check if cookieString is not null
* Android Request Builder to correctly build the endpoint including queryStrings
> fix: android generic & api clients

- android/src/main/java/com/mattermost/networkclient/interceptors/BearerTokenInterceptor.kt
Add or Replace Auth header instead of always attempting to add it
> fix: android authorization header interceptor

- ios/Keychain.swift
Storing the token with `kSecAttrLabel` was working, however, retrieval was failing. While the [iOS documentation](https://developer.apple.com/documentation/security/ksecclassinternetpassword/) states that it is an applicable attribute, I'm wondering if it's applicable only to Keychain insertions and not retrieval queries? In any case, RNKeychain does not use the `kSecAttrLabel` when storing items of type `kSecClassInternetPassword` so I've removed it. The attribute `kSecAttrAccessible` is also now added in the `setToken` function.
> Remove use of kSecAttrLabel with token

- android/src/main/java/com/mattermost/networkclient/WebSocketEventListener.kt
- ios/WebSocketClient.swift
Some of the changes here are speculative, but after testing they seem to work just fine.
On the android side, the main problem is that we were receiving a `SocketException` instead of the other exceptions we were checking for. After a quick look, it seems safe to consider any error here probably is enough to close the connection. https://docs.oracle.com/javase/7/docs/api/java/net/SocketException.html
On the iphone side, the error is a bit more criptic, since it says not much more than error 57. After a big of googling, it seems to be the "websocket not connected" error, which also seems enough to close the websocket.
https://mattermost.atlassian.net/browse/MM-48802
> Fix not properly closing the websocket when starting airplane mode

- android/src/main/java/com/mattermost/networkclient/WebSocketClientModule.kt
- ios/WebSocketClient.swift
If we try to create a second websocket client too fast, there may be a race condition on the js side. By rejecting here, we avoid these issues.
Related to: https://github.com/mattermost/mattermost-mobile/pull/7185
> Reject promise if we try to create a ws client when we already have one

- android/src/main/java/com/mattermost/networkclient/NetworkClientBase.kt
If we pass the timeout option to and upload request, on Android was not listening, stopping it at 30 seconds.
This makes sure we are listening to this.
Fix https://mattermost.atlassian.net/browse/MM-53445
Fix https://github.com/mattermost/mattermost-mobile/issues/5818
> Listen for timeout options on upload

- android/src/main/java/com/mattermost/networkclient/NetworkClientBase.kt
- android/src/main/java/com/mattermost/networkclient/interceptors/TimeoutInterceptor.kt
- example/src/hooks/index.tsx
- example/src/utils/index.tsx
- src/APIClient/index.tsx
Tweak defaults to be more consistent with what React Native does. This may solve some problems with timeouts and request parallelization.
May solve https://mattermost.atlassian.net/browse/MM-49968
May solve https://github.com/mattermost/mattermost-mobile/issues/7021
> chore: tweak library defaults to be more consistent with what React Native does

- android/src/main/java/com/mattermost/networkclient/NetworkClientBase.kt
on Android if the timeouts for resource and request was passed as undefined, the creation of the client fails. in that case we will set it to 0 so that is set to no timeout
> fix: handle exception for Android timeouts config

- ios/APIClient.swift
The requests on iOS were not finishing as the parent function was not being called.
> fix: iOS correctly call super for urlSession delegate didCompleteWithError

- android/src/main/java/com/mattermost/networkclient/ApiClientModuleImpl.kt
- android/src/main/java/com/mattermost/networkclient/NetworkClient.kt
- android/src/main/java/com/mattermost/networkclient/enums/APIClientEvents.kt
- example/ios/Podfile.lock
- ios/Adapters/BearerAuthenticationAdapter.swift
- ios/ApiClient/ApiClientWrapper.swift
- ios/Delegates/ApiClientSessionDelegate.swift
- ios/Extensions/ApiClientError.swift
- ios/Extensions/Session+Extensions.swift
- ios/Extensions/SessionManager+Extensions.swift
- ios/GenericClient/GenericClientWrapper.swift
- ios/NetworkClient.swift
- ios/SessionManager.swift
- ios/WebSocket/WebSocketEngine.swift
- ios/WebSocket/WebSocketManager.swift
- ios/WebSocket/WebSocketWrapper.swift
As part of some of the requirements by XXXXX we needed to add support for SSL Pinning when building your own app.
The way is being built is a combination of the app and the network-client library, the app will hold the certificate assets while the network-library will use these certs to verify the server trust.
The cert files should have either a `.crt` or `.cer` extension while the name of the file must be the domain name.
The reason we support two files extensions per domain is to be able to build the app taking into account server cert rotation and minimizing the amount of app distribution through updates in order to validate the certs.
This SSL Pinning certificates should be included in the app at build time.
https://mattermost.atlassian.net/browse/MM-59055
> SSL Pinning support

- android/build.gradle
- android/src/main/java/com/mattermost/networkclient/ApiClientModuleImpl.kt
On Android we were using SharedPreferences to store the client certs and the session tokens but now the recommended way is to use [DataStore](https://developer.android.com/topic/libraries/architecture/datastore) instead
This PR migrates the current SharedPreferences to DataStore and starts using DataStore from this point onwards.
> Migrate SharedPreferences to DataStore

- android/src/main/java/com/mattermost/networkclient/ApiClientModuleImpl.kt
- android/src/main/java/com/mattermost/networkclient/NetworkClient.kt
In some cases where the app is not running we were hitting the issue `ERROR ReactNative: Error processing push notification error=Attempt to invoke virtual method 'boolean com.mattermost.networkclient.ApiClientModuleImpl.hasClientFor(okhttp3.HttpUrl)' on a null object reference`
basically this happened as the module was not initialized, so now we are forcing it to init in some places where the context is available but it cannot be cast as ReactApplicationContext, this changes ensures that the available context is capable of initializing the module.
Once this PR is merged and library release will be submitting the next PR that goes with this.
> fix(android): move from ReactApplicationContext to Context to use the library from native code

- ios/patches/Alamofire+5.9.1.diff
This patches the download progress in a way that handles the header of X-Uncompressed-Content-Length regardless of the lettercase
> fix(ios): patch download progress to handle X-Uncompressed-Content-Length

- android/src/main/java/com/mattermost/networkclient/WebSocketClientModuleImpl.kt
By chance saw a message in the logs about "Excesive number of pending callbacks", pointing to "sendDataFor" on the "WebsocketClient".
After checking the code, I saw we are not resolving some of the promises for the websocket client. This fixes that.
NONE
> fix(android): fix unresolved promises on websocket client
